### ISSUE TITLE
Basic user interface

### ISSUE THREAD

**Issue by CeraStroh** [CeraStroh/study-application#1]
As a student, I want to navigate between webpages so that I can access the Study Sets on my account.

**Comment by CeraStroh** [comment]
## Conditions of Satisfaction
- At least two web pages (for the Home page and a page to display a Study Set)
- A navigation bar on the side
- UI components can render on the pages (but they do not have to do anything yet when clicked on)

### Tasks
- [x] Create application (1)
- [x] Run development server (1)
- [x] Set up root directory (2)
- [x] Create navigation component (2)
- [x] Create layout with side navigation (2)
- [x] Optimize navigation with `<Link>` component (1)
- [x] Enable UI pattern of showing active links (2)
