### ISSUE TITLE
Study Set modification

### ISSUE THREAD

**Issue by CeraStroh** [CeraStroh/study-application#3]
As a student, I want to edit my Study Sets so that I can make easy changes and fix mistakes without needing to create a whole new Study Set just to update it.

**Comment by CeraStroh** [comment]
## Conditions of Satisfaction
- An "Edit" button on a Study Set will redirect to a page with the Study Set filled in with its contents
- The changes should be visible on the Study Set and added to a database after the user clicks the "Save" button
- The database will be protected from SQL injection attacks
- An error will display if a user tries to have more than 50 Term-Definition pairs in a single Study Set
- An error will display if a user has more than 255 characters in a text input on a Study Set

### Tasks
- [x] Create an "Edit" button (1)
- [x] Create Dynamic Route Segments with the Study Set ID (2)
- [x] Fetch the Study Set information from the database with React Server Components and experiment with how data is stored in the database (5)
- [x] Display a "Save" button at the bottom (1)
- [x] Use React Server Actions & SQL to mutate data and add the changes to the database (2)

**Comment by CeraStroh** [comment]
3/14 Progress - 1 hour
Corrected some merging issues from Issue #2 and main
Completed "Edit" button, Dynamic Route Segments, & "Save" button tasks.

**Comment by CeraStroh** [comment]
3/18 Progress - 1 hour
Created functions to fetch terms and definitions.

Idea: Try mapping out each term and each definition in the edit-form. Double-check how each one can be determined in an array in the same Study Set since they are not separated by rows.

**Comment by CeraStroh** [comment]
3/19 Progress - 1 hour
Tried fetching terms differently to no avail.
Called fetch functions for terms and definitions in parallel in `edit-form`.

**Comment by CeraStroh** [comment]
Idea: create a hidden input field that has a value of Terms-Definitions pairs variable, submit it to the createStudySet() server action & add to database in 1 big array, set the pairs variable to the big array from the database
Also add the solution for the auto-submit problem in the create-form to the edit-form.

**Comment by CeraStroh** [comment]
3/30 Progress - 45 minutes

**Comment by CeraStroh** [comment]
4/2 - 1 hour
Unable to make the types of the pairs array match to set study_content to the initial pairs variable on the edit-form but it still seems like this solution will be the most effective if it actually works.

**Comment by CeraStroh** [comment]
4/3 - 2 hours
Completed Fetch the Study Set information & add changes to database tasks
Tested solution and cleaned up code
Fixed merge conflicts between modification & deletion
PR into `main` #[38](https://github.com/CeraStroh/study-application/pull/38/)
PR into `develop` #[39](https://github.com/CeraStroh/study-application/pull/39)
