### ISSUE TITLE
Create account option

### ISSUE THREAD

**Issue by CeraStroh** [CeraStroh/study-application#42]
As a student, I want to be able to create a new user account so that I can still use the application to study even if I do not have an existing account.

**Comment by CeraStroh** [comment]
## Conditions of Satisfaction
- A user will be able to click a "Create account" button on the login form that will redirect to a form to fill in a username, email, and password
- The form input will be added to the database so the user can sign in with the same credentials

### Tasks
- [x] Add a "Create account" button (1)
- [x] Create the form to fill in a username, email, password, and security question answer (3)
- [x] Use Zod to add form validation for the inputs (3)
- [x] Create a createAccount() server action to hash the password and insert the user's information into the database (4)
- [x] Fetch the user_id from the current session to manage Study Sets (3)

**Comment by CeraStroh** [comment]
4/30 Progress - 1 hour
Added security columns to database, filled in an example user's security question and answer
Created register path
Completed "Create account" button, Create the form, and Create a createAccount() server action tasks (8 points)

**Comment by CeraStroh** [comment]
5/1 Progress - 30 minutes
Worked on fetching the current session

**Comment by CeraStroh** [comment]
5/2 Progress - 1.5 hours
Continued researching how to use the current session

**Comment by CeraStroh** [comment]
5/3 Progress - 2.5 hours
Successfully used the token and session callbacks to fetch the current user session name and id to complete the task (3). Also fixed errors so the branch will be successfully deployed.
[Get session documentation](https://authjs.dev/getting-started/session-management/get-session)
[Extending the session documentation](https://authjs.dev/guides/extending-the-session)

**Comment by CeraStroh** [comment]
5/4 Progress - 1.75 hours
Completed form validation task
Conducted final tests
[PR to `develop` branch](https://github.com/CeraStroh/study-application/pull/46)
[PR to `main` branch](https://github.com/CeraStroh/study-application/pull/47)
