### ISSUE TITLE
Reset password option

### ISSUE THREAD

**Issue by CeraStroh** [CeraStroh/study-application#43]
As a student, I want to be able to reset my password so that I can still use the application to study even if I do not remember my password.

**Comment by CeraStroh** [comment]
## Conditions of Satisfaction
- A user will be able to click a "Forgot password" button on the login form that will allow them to change their password as long as they can input a correct username, password, and answer to the security question
- An error will be displayed if the input is incorrect
- The new password will be hashed and updated in the database

### Tasks
- [ ] Add a "Forgot password" button (1)
- [ ] Create the form to fill in a username, email, and answer to a displayed security question (3)
- [ ] Use Zod to add form validation for the inputs (3)
- [ ] Create an updatePassword(password) server action to hash the password and update it in the database (4)
