### ISSUE TITLE
Flashcard study practice

### ISSUE THREAD

**Issue by CeraStroh** [CeraStroh/study-application#5]
As a student, I want to study with flashcards so that I can practice remembering and recollecting concepts based on the prompts.

**Comment by CeraStroh** [comment]
## Conditions of Satisfaction
- Users can view all of the Terms and Definitions of a Study Set listed out on its own webpage
- Users should be able to click on the card or a button to display the other side of the card
- Clicking a "Next" button under the card should show the next card
- An optional "Start Over" button will reset the process and display the first card again
- A form shows an option to switch between answering with Terms or Definitions, as well as the option to keep score or shuffle the order
- If the user opts to keep score, there will be two buttons to mark whether the user answered correctly or incorrectly

### Tasks
- [x] Create a Study Set's own webpage using its set_id in the URL (2)
- [x] List all of the Terms and Definitions for one Study Set in a table on the Set's webpage (3)
- [x] Create a card component that has two properties for the front (prompt) and back (answer) (3)
- [x] Create form (2)
- [x] Add Terms/Definitions toggle that enables what user wants to answer with, sets  `front == term` and `back == definition` by default, otherwise `front == definition` and `back == term` (2)
- [x] Add "Keep score?" yes/no toggle option (1)
- [x] Add "Shuffle?" yes/no option (1)
- [x] Add "Correct" and "Incorrect" buttons under card component that displays the number of incorrect and correct answers if "Keep score?" is toggled to yes (2)
- [x] Create function that populates cards with Terms and Definitions from `studyset` table (4)
- [x] Add functionality to randomly change the order of the Term-Definition pairs (3)
- [x] Show back when card is clicked on (2)
- [x] Add "Next" button to display next card (2)
- [x] Add "Start Over" button that resets the displayed card to the first pair in the Study Set (2)

**Comment by CeraStroh** [comment]
4/8 Progress - 2 hours
Idea: Have a flashcard take 2 parameters (term & definition), set pairs index on flashcard practice page

**Comment by CeraStroh** [comment]
4/10 Progress - 1 hour 45 minutes
Created form that asked popup questions
Displayed a study set's contents

**Comment by CeraStroh** [comment]
4/22 Progress - 1 hour
Worked on Flashcard component

**Comment by CeraStroh** [comment]
4/23 Progress - 40 minutes
Worked on Flashcard component, added fix for autosubmit error in edit form
Completed function that populates cards task (4 points)

**Comment by CeraStroh** [comment]
4/25 Progress - 1 hour
Completed create a card component, shuffle option, show back when card is clicked, add "next" button (& "previous" button), and add "start over" button tasks (10 points)

**Comment by CeraStroh** [comment]
4/26 Progress - 2 hours
Connected flashcard settings with flashcard functionality
Idea: Use a [popper](https://mui.com/material-ui/react-popper/) to hide the settings while the user is studying

**Comment by CeraStroh** [comment]
4/27 Progress -1.5 hours
Completed "incorrect" and "correct" buttons task & finished score functionality
Started shuffle functionality

**Comment by CeraStroh** [comment]
4/28 Progress - 1 hour
Added shuffle functionality but there are problems with the logic

**Comment by CeraStroh** [comment]
4/29 Progress - 2 hours 10 minutes
[PR to merge with `develop`](https://github.com/CeraStroh/study-application/pull/45)
[PR to merge with `main`](https://github.com/CeraStroh/study-application/pull/44)
