### ISSUE TITLE
User authentication and authorization

### ISSUE THREAD

**Issue by CeraStroh** [CeraStroh/study-application#7]
As a student, I want to have my own account that only I can access so that I can save my progress and Study Sets in addition to protecting my information from being publicly accessed.

**Comment by CeraStroh** [comment]
## Conditions of Satisfaction
- A login page will be displayed if a user is not logged in.
- A user will be logged in if they submit the correct username-password pair that is connected to an existing user in the database
- A user will be logged out if they click the "Sign out" button on the navigation bar

### Tasks
- [x] Create a login page (1)
- [x] Install NextAuth.js by running `npm install next-auth@beta` (1)
- [x] Generate a secret key for the development and production environments (2)
- [x] Create an `auth.config.ts` file (1)
- [x] Add Middleware authorized callbacks and provider options (2)
- [x] Create a `middleware.ts` file with providers (2)
- [x] Create an `auth.ts` file (2)
- [x] Connect the auth logic with the login form (2)
- [x] Add the login functionality (3)
- [x] Add the logout functionality (1)

**Comment by CeraStroh** [comment]
4/6 Progress - 1.5 hours
Completed all tasks but the last "logout functionality" task

**Comment by CeraStroh** [comment]
4/7 Progress - 2.25 hours
Completed the "logout functionality" task, tested, and debugged any errors
Started an unlisted "create user functionality" task
TODO: Debug sql query to createUser(), change how sets will be managed & displayed with session user_id

**Comment by CeraStroh** [comment]
4/8 Progress - 45 minutes
- Decided to make the createUser functionality a different user story because it is out of scope with this story
- Made a new branch called `feature/create-user` based on this `7-user-authentication-and-authorization` branch and removed the out-of-scope changes on this branch
- PR #40 to merge with `develop`
- PR #41 to merge with `main`
